# Use an official Node runtime as the base image
FROM node:20.17.0-alpine

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose port 7000
EXPOSE 7000

# Start the Node.js server
CMD ["npm", "run", "dev"]